# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "Distribute Build"
lane :distributeBuild do |options|
    gradle(
        task: "assemble",
        flavor: options[:flavor],
        build_type: "release"
    )
    message = last_git_commit[:message]
    File.write("./changelog.txt", message)
end

desc "Run Unit Tests"
lane :unit_tests do |options|
  gradle(
    task: "test",
    flavor: options[:flavor],
    build_type: "release"
  )
end
