# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "Distribute Dev"
lane :distributeDev do

    # Unit Test
    gradle(task: "testDevDebugUnitTest")

    # Build apk
    build_android_app(task: "app:assembleDevRelease")
    app_apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

    # TODO ui test

    # create change log
    message = last_git_commit[:message]
    File.write("./changelog.txt", message)

    # Distribute to firebase
    firebase_app_distribution(
      app: "1:137656115448:android:9a5c0c04101f6373c11b0d",
      apk_path: app_apk_path,
      groups: "Developers",
      release_notes_file: "fastlane/changelog.txt",
      firebase_cli_path: "/usr/local/bin/firebase"
    )

end